In [1]:
!conda install -c conda-forge geopy --yes 
!conda install -c conda-forge folium=0.5.0 --yes

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

In [2]:
!conda install -c conda-forge geocoder --yes

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

In [3]:
import requests
import pandas as pd
import numpy as np
import json
import matplotlib
import matplotlib.cm as cm
import matplotlib.colors as colors
from geopy.geocoders import Nominatim
from pandas.io.json import json_normalize
from sklearn.cluster import KMeans
import folium

In [4]:
# Downloading data and showing first 5 rows
#Data was scraped by the help of external service
path = 'table-1.csv'
df = pd.read_csv(path)
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [5]:
# Processing of data
# First of all, we remove all rows where Borough isn't assigned
df.drop(df[df['Borough'] == 'Not assigned'].index,axis=0,inplace=True)
# If Borough is shown, but neighbourhood is unknown, we will consider that Borough = Neighbourhood
df.replace(df[df['Neighbourhood'] == 'Not assigned'].index,df['Borough'][df[df['Neighbourhood'] == 'Not assigned'].index])
# If more than one neighborhood exist in postcode area, we will combine rows
df_new = df.groupby(['Postcode'],as_index=False).agg(lambda x : x.sum() if x.dtype=='float64' else ' '.join(x))
#Remove repeating words in Borough column
newbor = [] #Create a list with clear names
for val in df_new['Borough']:
    val = val.split(' ')
    newbor.append(val[0])
df_new['Borough'] = newbor #Append it instead of old ones
print(df_new.shape)
df_new

(103, 3)

    Postcode      Borough                                      Neighbourhood
0        M1B  Scarborough                                      Rouge Malvern
1        M1C  Scarborough               Highland Creek Rouge Hill Port Union
2        M1E  Scarborough                    Guildwood Morningside West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village Martin Grove Gardens Richvie...
101      M9V    Etobicoke  Albion Gardens Beaumond Heights Humbergate Jam...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [6]:
##For some reason this code doesn't work so we just download dataset
#import geocoder # import geocoder
#postal_codes = df_new['Postcode']
#lats = []
#longs = []
#for postal_code in postal_codes:
#    # initialize your variable to None
#    lat_lng_coords = None

    # loop until you get the coordinates
#    while(lat_lng_coords is None):
#        e = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
#        lat_lng_coords = e.latlng
#    latitude = lat_lng_coords[0]
#    longitude = lat_lng_coords[1]
#    lats.append(latitude)
#    longs.append(longitude)

In [7]:
path = 'http://cocl.us/Geospatial_data'
geospatial = pd.read_csv(path)

In [8]:
geospatial.head()
geospatial.shape

(103, 3)

In [9]:
df_new['Latitude'] = geospatial['Latitude']
df_new['Longitude'] = geospatial['Longitude']
df_new

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,Rouge Malvern,43.806686,-79.194353
1,M1C,Scarborough,Highland Creek Rouge Hill Port Union,43.784535,-79.160497
2,M1E,Scarborough,Guildwood Morningside West Hill,43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,Kingsview Village Martin Grove Gardens Richvie...,43.688905,-79.554724
101,M9V,Etobicoke,Albion Gardens Beaumond Heights Humbergate Jam...,43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054